version: '1.2'
services:
  mysql:
    image: mysql:latest
    container_name: bookstore-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./datas:/var/lib/mysql
      - ./scripts_sql:/docker-entrypoint-initdb.d