version: "1.2"
services:
  mysql:
    image: mysql:latest
    container_name: bookstore-database
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./datas:/var/lib/mysql
      - ./scripts_sql:/docker-entrypoint-initdb.d
